# Generated by Django 4.2.3 on 2023-09-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_recipes_image_recipes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Изображение'),
        ),
    ]
